volumes:
  n8n_storage:
  # postgres_storage:

networks:
  n8n-local:

services:
  # postgres:
  #   image: postgres:latest
  #   networks: ['n8n-local']
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER
  #     - POSTGRES_PASSWORD
  #     - POSTGRES_DB
  #     - PGDATA=/var/lib/postgresql/data
  #   volumes:
  #     - postgres_storage:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    networks: ['n8n-local']
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=sqlite
      # - DB_POSTGRESDB_HOST=postgres
      # - DB_POSTGRESDB_USER=${POSTGRES_USER}
      # - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_SECURE_COOKIE=false
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_HOST=localhost
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
    # links:
    #   - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
      # - ./nodes:/home/node/.n8n/custom/node_modules/custom_nodes
    # depends_on:
    #   postgres:
    #     condition: service_healthy
